
namespace FootballClubManagementSystem
{
	partial class frmClub
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}

		#region Windows Form Designer generated code

		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmClub));
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges15 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges16 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges17 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges18 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges19 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges20 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			this.club_ptbLogo = new Bunifu.UI.WinForms.BunifuPictureBox();
			this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
			this.club_btnUploadAwayJersey = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.club_ptbAwayJersey = new Bunifu.UI.WinForms.BunifuPictureBox();
			this.club_btnUploadHomeJersey = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.club_ptbHomeJersey = new Bunifu.UI.WinForms.BunifuPictureBox();
			this.club_btnUploadLogo = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.club_txtNameClub = new Bunifu.UI.WinForms.BunifuTextBox();
			this.club_txtPhoneNumber = new Bunifu.UI.WinForms.BunifuTextBox();
			this.club_txtEmail = new Bunifu.UI.WinForms.BunifuTextBox();
			this.club_txtAddress = new Bunifu.UI.WinForms.BunifuTextBox();
			this.club_btnCancel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.club_btnOK = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.club_btnLogOut = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.club_btnBackHome = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.bunifuGradientPanel2 = new Bunifu.UI.WinForms.BunifuGradientPanel();
			((System.ComponentModel.ISupportInitialize)(this.club_ptbLogo)).BeginInit();
			this.bunifuGradientPanel1.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.club_ptbAwayJersey)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.club_ptbHomeJersey)).BeginInit();
			this.bunifuGradientPanel2.SuspendLayout();
			this.SuspendLayout();
			// 
			// club_ptbLogo
			// 
			this.club_ptbLogo.AllowFocused = false;
			this.club_ptbLogo.Anchor = System.Windows.Forms.AnchorStyles.None;
			this.club_ptbLogo.AutoSizeHeight = true;
			this.club_ptbLogo.BorderRadius = 50;
			this.club_ptbLogo.Image = ((System.Drawing.Image)(resources.GetObject("club_ptbLogo.Image")));
			this.club_ptbLogo.IsCircle = true;
			this.club_ptbLogo.Location = new System.Drawing.Point(49, 23);
			this.club_ptbLogo.Name = "club_ptbLogo";
			this.club_ptbLogo.Size = new System.Drawing.Size(100, 100);
			this.club_ptbLogo.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.club_ptbLogo.TabIndex = 0;
			this.club_ptbLogo.TabStop = false;
			this.club_ptbLogo.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
			// 
			// bunifuGradientPanel1
			// 
			this.bunifuGradientPanel1.BackColor = System.Drawing.Color.Transparent;
			this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
			this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
			this.bunifuGradientPanel1.BorderRadius = 1;
			this.bunifuGradientPanel1.Controls.Add(this.club_btnUploadAwayJersey);
			this.bunifuGradientPanel1.Controls.Add(this.club_ptbAwayJersey);
			this.bunifuGradientPanel1.Controls.Add(this.club_btnUploadHomeJersey);
			this.bunifuGradientPanel1.Controls.Add(this.club_ptbHomeJersey);
			this.bunifuGradientPanel1.Controls.Add(this.club_btnUploadLogo);
			this.bunifuGradientPanel1.Controls.Add(this.club_ptbLogo);
			this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(92)))), ((int)(((byte)(188)))));
			this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.DeepPink;
			this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.DodgerBlue;
			this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(198)))), ((int)(((byte)(60)))), ((int)(((byte)(212)))));
			this.bunifuGradientPanel1.Location = new System.Drawing.Point(-1, 0);
			this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
			this.bunifuGradientPanel1.Quality = 10;
			this.bunifuGradientPanel1.Size = new System.Drawing.Size(199, 553);
			this.bunifuGradientPanel1.TabIndex = 4;
			// 
			// club_btnUploadAwayJersey
			// 
			this.club_btnUploadAwayJersey.AllowAnimations = true;
			this.club_btnUploadAwayJersey.AllowMouseEffects = true;
			this.club_btnUploadAwayJersey.AllowToggling = false;
			this.club_btnUploadAwayJersey.AnimationSpeed = 200;
			this.club_btnUploadAwayJersey.AutoGenerateColors = false;
			this.club_btnUploadAwayJersey.AutoRoundBorders = false;
			this.club_btnUploadAwayJersey.AutoSizeLeftIcon = true;
			this.club_btnUploadAwayJersey.AutoSizeRightIcon = true;
			this.club_btnUploadAwayJersey.BackColor = System.Drawing.Color.Transparent;
			this.club_btnUploadAwayJersey.BackColor1 = System.Drawing.Color.DodgerBlue;
			this.club_btnUploadAwayJersey.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("club_btnUploadAwayJersey.BackgroundImage")));
			this.club_btnUploadAwayJersey.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnUploadAwayJersey.ButtonText = "Away Jersey";
			this.club_btnUploadAwayJersey.ButtonTextMarginLeft = 0;
			this.club_btnUploadAwayJersey.ColorContrastOnClick = 45;
			this.club_btnUploadAwayJersey.ColorContrastOnHover = 45;
			this.club_btnUploadAwayJersey.Cursor = System.Windows.Forms.Cursors.Hand;
			borderEdges15.BottomLeft = true;
			borderEdges15.BottomRight = true;
			borderEdges15.TopLeft = true;
			borderEdges15.TopRight = true;
			this.club_btnUploadAwayJersey.CustomizableEdges = borderEdges15;
			this.club_btnUploadAwayJersey.DialogResult = System.Windows.Forms.DialogResult.None;
			this.club_btnUploadAwayJersey.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.club_btnUploadAwayJersey.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.club_btnUploadAwayJersey.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.club_btnUploadAwayJersey.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			this.club_btnUploadAwayJersey.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.club_btnUploadAwayJersey.ForeColor = System.Drawing.Color.White;
			this.club_btnUploadAwayJersey.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.club_btnUploadAwayJersey.IconLeftCursor = System.Windows.Forms.Cursors.Default;
			this.club_btnUploadAwayJersey.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
			this.club_btnUploadAwayJersey.IconMarginLeft = 11;
			this.club_btnUploadAwayJersey.IconPadding = 10;
			this.club_btnUploadAwayJersey.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
			this.club_btnUploadAwayJersey.IconRightCursor = System.Windows.Forms.Cursors.Default;
			this.club_btnUploadAwayJersey.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
			this.club_btnUploadAwayJersey.IconSize = 25;
			this.club_btnUploadAwayJersey.IdleBorderColor = System.Drawing.Color.DodgerBlue;
			this.club_btnUploadAwayJersey.IdleBorderRadius = 1;
			this.club_btnUploadAwayJersey.IdleBorderThickness = 1;
			this.club_btnUploadAwayJersey.IdleFillColor = System.Drawing.Color.DodgerBlue;
			this.club_btnUploadAwayJersey.IdleIconLeftImage = null;
			this.club_btnUploadAwayJersey.IdleIconRightImage = null;
			this.club_btnUploadAwayJersey.IndicateFocus = false;
			this.club_btnUploadAwayJersey.Location = new System.Drawing.Point(20, 484);
			this.club_btnUploadAwayJersey.Name = "club_btnUploadAwayJersey";
			this.club_btnUploadAwayJersey.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.club_btnUploadAwayJersey.OnDisabledState.BorderRadius = 1;
			this.club_btnUploadAwayJersey.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnUploadAwayJersey.OnDisabledState.BorderThickness = 1;
			this.club_btnUploadAwayJersey.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.club_btnUploadAwayJersey.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.club_btnUploadAwayJersey.OnDisabledState.IconLeftImage = null;
			this.club_btnUploadAwayJersey.OnDisabledState.IconRightImage = null;
			this.club_btnUploadAwayJersey.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.club_btnUploadAwayJersey.onHoverState.BorderRadius = 1;
			this.club_btnUploadAwayJersey.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnUploadAwayJersey.onHoverState.BorderThickness = 1;
			this.club_btnUploadAwayJersey.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.club_btnUploadAwayJersey.onHoverState.ForeColor = System.Drawing.Color.White;
			this.club_btnUploadAwayJersey.onHoverState.IconLeftImage = null;
			this.club_btnUploadAwayJersey.onHoverState.IconRightImage = null;
			this.club_btnUploadAwayJersey.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
			this.club_btnUploadAwayJersey.OnIdleState.BorderRadius = 1;
			this.club_btnUploadAwayJersey.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnUploadAwayJersey.OnIdleState.BorderThickness = 1;
			this.club_btnUploadAwayJersey.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
			this.club_btnUploadAwayJersey.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.club_btnUploadAwayJersey.OnIdleState.IconLeftImage = null;
			this.club_btnUploadAwayJersey.OnIdleState.IconRightImage = null;
			this.club_btnUploadAwayJersey.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.club_btnUploadAwayJersey.OnPressedState.BorderRadius = 1;
			this.club_btnUploadAwayJersey.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnUploadAwayJersey.OnPressedState.BorderThickness = 1;
			this.club_btnUploadAwayJersey.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.club_btnUploadAwayJersey.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.club_btnUploadAwayJersey.OnPressedState.IconLeftImage = null;
			this.club_btnUploadAwayJersey.OnPressedState.IconRightImage = null;
			this.club_btnUploadAwayJersey.Size = new System.Drawing.Size(158, 46);
			this.club_btnUploadAwayJersey.TabIndex = 6;
			this.club_btnUploadAwayJersey.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.club_btnUploadAwayJersey.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			this.club_btnUploadAwayJersey.TextMarginLeft = 0;
			this.club_btnUploadAwayJersey.TextPadding = new System.Windows.Forms.Padding(0);
			this.club_btnUploadAwayJersey.UseDefaultRadiusAndThickness = true;
			this.club_btnUploadAwayJersey.Click += new System.EventHandler(this.club_btnUploadAwayJersey_Click);
			// 
			// club_ptbAwayJersey
			// 
			this.club_ptbAwayJersey.AllowFocused = false;
			this.club_ptbAwayJersey.Anchor = System.Windows.Forms.AnchorStyles.None;
			this.club_ptbAwayJersey.AutoSizeHeight = true;
			this.club_ptbAwayJersey.BorderRadius = 50;
			this.club_ptbAwayJersey.Image = ((System.Drawing.Image)(resources.GetObject("club_ptbAwayJersey.Image")));
			this.club_ptbAwayJersey.IsCircle = true;
			this.club_ptbAwayJersey.Location = new System.Drawing.Point(48, 372);
			this.club_ptbAwayJersey.Name = "club_ptbAwayJersey";
			this.club_ptbAwayJersey.Size = new System.Drawing.Size(100, 100);
			this.club_ptbAwayJersey.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.club_ptbAwayJersey.TabIndex = 103;
			this.club_ptbAwayJersey.TabStop = false;
			this.club_ptbAwayJersey.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
			// 
			// club_btnUploadHomeJersey
			// 
			this.club_btnUploadHomeJersey.AllowAnimations = true;
			this.club_btnUploadHomeJersey.AllowMouseEffects = true;
			this.club_btnUploadHomeJersey.AllowToggling = false;
			this.club_btnUploadHomeJersey.AnimationSpeed = 200;
			this.club_btnUploadHomeJersey.AutoGenerateColors = false;
			this.club_btnUploadHomeJersey.AutoRoundBorders = false;
			this.club_btnUploadHomeJersey.AutoSizeLeftIcon = true;
			this.club_btnUploadHomeJersey.AutoSizeRightIcon = true;
			this.club_btnUploadHomeJersey.BackColor = System.Drawing.Color.Transparent;
			this.club_btnUploadHomeJersey.BackColor1 = System.Drawing.Color.DodgerBlue;
			this.club_btnUploadHomeJersey.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("club_btnUploadHomeJersey.BackgroundImage")));
			this.club_btnUploadHomeJersey.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnUploadHomeJersey.ButtonText = "Home Jersey";
			this.club_btnUploadHomeJersey.ButtonTextMarginLeft = 0;
			this.club_btnUploadHomeJersey.ColorContrastOnClick = 45;
			this.club_btnUploadHomeJersey.ColorContrastOnHover = 45;
			this.club_btnUploadHomeJersey.Cursor = System.Windows.Forms.Cursors.Hand;
			borderEdges16.BottomLeft = true;
			borderEdges16.BottomRight = true;
			borderEdges16.TopLeft = true;
			borderEdges16.TopRight = true;
			this.club_btnUploadHomeJersey.CustomizableEdges = borderEdges16;
			this.club_btnUploadHomeJersey.DialogResult = System.Windows.Forms.DialogResult.None;
			this.club_btnUploadHomeJersey.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.club_btnUploadHomeJersey.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.club_btnUploadHomeJersey.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.club_btnUploadHomeJersey.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			this.club_btnUploadHomeJersey.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.club_btnUploadHomeJersey.ForeColor = System.Drawing.Color.White;
			this.club_btnUploadHomeJersey.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.club_btnUploadHomeJersey.IconLeftCursor = System.Windows.Forms.Cursors.Default;
			this.club_btnUploadHomeJersey.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
			this.club_btnUploadHomeJersey.IconMarginLeft = 11;
			this.club_btnUploadHomeJersey.IconPadding = 10;
			this.club_btnUploadHomeJersey.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
			this.club_btnUploadHomeJersey.IconRightCursor = System.Windows.Forms.Cursors.Default;
			this.club_btnUploadHomeJersey.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
			this.club_btnUploadHomeJersey.IconSize = 25;
			this.club_btnUploadHomeJersey.IdleBorderColor = System.Drawing.Color.DodgerBlue;
			this.club_btnUploadHomeJersey.IdleBorderRadius = 1;
			this.club_btnUploadHomeJersey.IdleBorderThickness = 1;
			this.club_btnUploadHomeJersey.IdleFillColor = System.Drawing.Color.DodgerBlue;
			this.club_btnUploadHomeJersey.IdleIconLeftImage = null;
			this.club_btnUploadHomeJersey.IdleIconRightImage = null;
			this.club_btnUploadHomeJersey.IndicateFocus = false;
			this.club_btnUploadHomeJersey.Location = new System.Drawing.Point(20, 304);
			this.club_btnUploadHomeJersey.Name = "club_btnUploadHomeJersey";
			this.club_btnUploadHomeJersey.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.club_btnUploadHomeJersey.OnDisabledState.BorderRadius = 1;
			this.club_btnUploadHomeJersey.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnUploadHomeJersey.OnDisabledState.BorderThickness = 1;
			this.club_btnUploadHomeJersey.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.club_btnUploadHomeJersey.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.club_btnUploadHomeJersey.OnDisabledState.IconLeftImage = null;
			this.club_btnUploadHomeJersey.OnDisabledState.IconRightImage = null;
			this.club_btnUploadHomeJersey.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.club_btnUploadHomeJersey.onHoverState.BorderRadius = 1;
			this.club_btnUploadHomeJersey.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnUploadHomeJersey.onHoverState.BorderThickness = 1;
			this.club_btnUploadHomeJersey.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.club_btnUploadHomeJersey.onHoverState.ForeColor = System.Drawing.Color.White;
			this.club_btnUploadHomeJersey.onHoverState.IconLeftImage = null;
			this.club_btnUploadHomeJersey.onHoverState.IconRightImage = null;
			this.club_btnUploadHomeJersey.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
			this.club_btnUploadHomeJersey.OnIdleState.BorderRadius = 1;
			this.club_btnUploadHomeJersey.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnUploadHomeJersey.OnIdleState.BorderThickness = 1;
			this.club_btnUploadHomeJersey.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
			this.club_btnUploadHomeJersey.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.club_btnUploadHomeJersey.OnIdleState.IconLeftImage = null;
			this.club_btnUploadHomeJersey.OnIdleState.IconRightImage = null;
			this.club_btnUploadHomeJersey.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.club_btnUploadHomeJersey.OnPressedState.BorderRadius = 1;
			this.club_btnUploadHomeJersey.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnUploadHomeJersey.OnPressedState.BorderThickness = 1;
			this.club_btnUploadHomeJersey.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.club_btnUploadHomeJersey.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.club_btnUploadHomeJersey.OnPressedState.IconLeftImage = null;
			this.club_btnUploadHomeJersey.OnPressedState.IconRightImage = null;
			this.club_btnUploadHomeJersey.Size = new System.Drawing.Size(158, 46);
			this.club_btnUploadHomeJersey.TabIndex = 5;
			this.club_btnUploadHomeJersey.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.club_btnUploadHomeJersey.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			this.club_btnUploadHomeJersey.TextMarginLeft = 0;
			this.club_btnUploadHomeJersey.TextPadding = new System.Windows.Forms.Padding(0);
			this.club_btnUploadHomeJersey.UseDefaultRadiusAndThickness = true;
			this.club_btnUploadHomeJersey.Click += new System.EventHandler(this.club_btnUploadHomeJersey_Click);
			// 
			// club_ptbHomeJersey
			// 
			this.club_ptbHomeJersey.AllowFocused = false;
			this.club_ptbHomeJersey.Anchor = System.Windows.Forms.AnchorStyles.None;
			this.club_ptbHomeJersey.AutoSizeHeight = true;
			this.club_ptbHomeJersey.BorderRadius = 50;
			this.club_ptbHomeJersey.Image = ((System.Drawing.Image)(resources.GetObject("club_ptbHomeJersey.Image")));
			this.club_ptbHomeJersey.IsCircle = true;
			this.club_ptbHomeJersey.Location = new System.Drawing.Point(48, 198);
			this.club_ptbHomeJersey.Name = "club_ptbHomeJersey";
			this.club_ptbHomeJersey.Size = new System.Drawing.Size(100, 100);
			this.club_ptbHomeJersey.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.club_ptbHomeJersey.TabIndex = 101;
			this.club_ptbHomeJersey.TabStop = false;
			this.club_ptbHomeJersey.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
			// 
			// club_btnUploadLogo
			// 
			this.club_btnUploadLogo.AllowAnimations = true;
			this.club_btnUploadLogo.AllowMouseEffects = true;
			this.club_btnUploadLogo.AllowToggling = false;
			this.club_btnUploadLogo.AnimationSpeed = 200;
			this.club_btnUploadLogo.AutoGenerateColors = false;
			this.club_btnUploadLogo.AutoRoundBorders = false;
			this.club_btnUploadLogo.AutoSizeLeftIcon = true;
			this.club_btnUploadLogo.AutoSizeRightIcon = true;
			this.club_btnUploadLogo.BackColor = System.Drawing.Color.Transparent;
			this.club_btnUploadLogo.BackColor1 = System.Drawing.Color.DodgerBlue;
			this.club_btnUploadLogo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("club_btnUploadLogo.BackgroundImage")));
			this.club_btnUploadLogo.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnUploadLogo.ButtonText = "Logo";
			this.club_btnUploadLogo.ButtonTextMarginLeft = 0;
			this.club_btnUploadLogo.ColorContrastOnClick = 45;
			this.club_btnUploadLogo.ColorContrastOnHover = 45;
			this.club_btnUploadLogo.Cursor = System.Windows.Forms.Cursors.Hand;
			borderEdges17.BottomLeft = true;
			borderEdges17.BottomRight = true;
			borderEdges17.TopLeft = true;
			borderEdges17.TopRight = true;
			this.club_btnUploadLogo.CustomizableEdges = borderEdges17;
			this.club_btnUploadLogo.DialogResult = System.Windows.Forms.DialogResult.None;
			this.club_btnUploadLogo.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.club_btnUploadLogo.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.club_btnUploadLogo.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.club_btnUploadLogo.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			this.club_btnUploadLogo.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.club_btnUploadLogo.ForeColor = System.Drawing.Color.White;
			this.club_btnUploadLogo.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.club_btnUploadLogo.IconLeftCursor = System.Windows.Forms.Cursors.Default;
			this.club_btnUploadLogo.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
			this.club_btnUploadLogo.IconMarginLeft = 11;
			this.club_btnUploadLogo.IconPadding = 10;
			this.club_btnUploadLogo.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
			this.club_btnUploadLogo.IconRightCursor = System.Windows.Forms.Cursors.Default;
			this.club_btnUploadLogo.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
			this.club_btnUploadLogo.IconSize = 25;
			this.club_btnUploadLogo.IdleBorderColor = System.Drawing.Color.DodgerBlue;
			this.club_btnUploadLogo.IdleBorderRadius = 1;
			this.club_btnUploadLogo.IdleBorderThickness = 1;
			this.club_btnUploadLogo.IdleFillColor = System.Drawing.Color.DodgerBlue;
			this.club_btnUploadLogo.IdleIconLeftImage = null;
			this.club_btnUploadLogo.IdleIconRightImage = null;
			this.club_btnUploadLogo.IndicateFocus = false;
			this.club_btnUploadLogo.Location = new System.Drawing.Point(21, 135);
			this.club_btnUploadLogo.Name = "club_btnUploadLogo";
			this.club_btnUploadLogo.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.club_btnUploadLogo.OnDisabledState.BorderRadius = 1;
			this.club_btnUploadLogo.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnUploadLogo.OnDisabledState.BorderThickness = 1;
			this.club_btnUploadLogo.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.club_btnUploadLogo.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.club_btnUploadLogo.OnDisabledState.IconLeftImage = null;
			this.club_btnUploadLogo.OnDisabledState.IconRightImage = null;
			this.club_btnUploadLogo.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.club_btnUploadLogo.onHoverState.BorderRadius = 1;
			this.club_btnUploadLogo.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnUploadLogo.onHoverState.BorderThickness = 1;
			this.club_btnUploadLogo.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.club_btnUploadLogo.onHoverState.ForeColor = System.Drawing.Color.White;
			this.club_btnUploadLogo.onHoverState.IconLeftImage = null;
			this.club_btnUploadLogo.onHoverState.IconRightImage = null;
			this.club_btnUploadLogo.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
			this.club_btnUploadLogo.OnIdleState.BorderRadius = 1;
			this.club_btnUploadLogo.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnUploadLogo.OnIdleState.BorderThickness = 1;
			this.club_btnUploadLogo.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
			this.club_btnUploadLogo.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.club_btnUploadLogo.OnIdleState.IconLeftImage = null;
			this.club_btnUploadLogo.OnIdleState.IconRightImage = null;
			this.club_btnUploadLogo.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.club_btnUploadLogo.OnPressedState.BorderRadius = 1;
			this.club_btnUploadLogo.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnUploadLogo.OnPressedState.BorderThickness = 1;
			this.club_btnUploadLogo.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.club_btnUploadLogo.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.club_btnUploadLogo.OnPressedState.IconLeftImage = null;
			this.club_btnUploadLogo.OnPressedState.IconRightImage = null;
			this.club_btnUploadLogo.Size = new System.Drawing.Size(158, 46);
			this.club_btnUploadLogo.TabIndex = 4;
			this.club_btnUploadLogo.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.club_btnUploadLogo.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			this.club_btnUploadLogo.TextMarginLeft = 0;
			this.club_btnUploadLogo.TextPadding = new System.Windows.Forms.Padding(0);
			this.club_btnUploadLogo.UseDefaultRadiusAndThickness = true;
			this.club_btnUploadLogo.Click += new System.EventHandler(this.club_btnUploadLogo_Click);
			// 
			// club_txtNameClub
			// 
			this.club_txtNameClub.AcceptsReturn = false;
			this.club_txtNameClub.AcceptsTab = false;
			this.club_txtNameClub.AnimationSpeed = 200;
			this.club_txtNameClub.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
			this.club_txtNameClub.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
			this.club_txtNameClub.BackColor = System.Drawing.Color.White;
			this.club_txtNameClub.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("club_txtNameClub.BackgroundImage")));
			this.club_txtNameClub.BorderColorActive = System.Drawing.Color.DodgerBlue;
			this.club_txtNameClub.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.club_txtNameClub.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.club_txtNameClub.BorderColorIdle = System.Drawing.Color.Silver;
			this.club_txtNameClub.BorderRadius = 5;
			this.club_txtNameClub.BorderThickness = 1;
			this.club_txtNameClub.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
			this.club_txtNameClub.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.club_txtNameClub.DefaultFont = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.club_txtNameClub.DefaultText = "";
			this.club_txtNameClub.FillColor = System.Drawing.Color.White;
			this.club_txtNameClub.ForeColor = System.Drawing.Color.Black;
			this.club_txtNameClub.HideSelection = true;
			this.club_txtNameClub.IconLeft = null;
			this.club_txtNameClub.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
			this.club_txtNameClub.IconPadding = 10;
			this.club_txtNameClub.IconRight = null;
			this.club_txtNameClub.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
			this.club_txtNameClub.Lines = new string[0];
			this.club_txtNameClub.Location = new System.Drawing.Point(29, 30);
			this.club_txtNameClub.MaxLength = 32767;
			this.club_txtNameClub.MinimumSize = new System.Drawing.Size(1, 1);
			this.club_txtNameClub.Modified = false;
			this.club_txtNameClub.Multiline = false;
			this.club_txtNameClub.Name = "club_txtNameClub";
			stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
			stateProperties33.FillColor = System.Drawing.Color.Empty;
			stateProperties33.ForeColor = System.Drawing.Color.Empty;
			stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.club_txtNameClub.OnActiveState = stateProperties33;
			stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
			stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
			stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
			this.club_txtNameClub.OnDisabledState = stateProperties34;
			stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			stateProperties35.FillColor = System.Drawing.Color.Empty;
			stateProperties35.ForeColor = System.Drawing.Color.Empty;
			stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.club_txtNameClub.OnHoverState = stateProperties35;
			stateProperties36.BorderColor = System.Drawing.Color.Silver;
			stateProperties36.FillColor = System.Drawing.Color.White;
			stateProperties36.ForeColor = System.Drawing.Color.Black;
			stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.club_txtNameClub.OnIdleState = stateProperties36;
			this.club_txtNameClub.Padding = new System.Windows.Forms.Padding(3);
			this.club_txtNameClub.PasswordChar = '\0';
			this.club_txtNameClub.PlaceholderForeColor = System.Drawing.Color.Silver;
			this.club_txtNameClub.PlaceholderText = "Name";
			this.club_txtNameClub.ReadOnly = false;
			this.club_txtNameClub.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.club_txtNameClub.SelectedText = "";
			this.club_txtNameClub.SelectionLength = 0;
			this.club_txtNameClub.SelectionStart = 0;
			this.club_txtNameClub.ShortcutsEnabled = true;
			this.club_txtNameClub.Size = new System.Drawing.Size(437, 46);
			this.club_txtNameClub.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
			this.club_txtNameClub.TabIndex = 1;
			this.club_txtNameClub.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.club_txtNameClub.TextMarginBottom = 0;
			this.club_txtNameClub.TextMarginLeft = 3;
			this.club_txtNameClub.TextMarginTop = 0;
			this.club_txtNameClub.TextPlaceholder = "Name";
			this.club_txtNameClub.UseSystemPasswordChar = false;
			this.club_txtNameClub.WordWrap = true;
			// 
			// club_txtPhoneNumber
			// 
			this.club_txtPhoneNumber.AcceptsReturn = false;
			this.club_txtPhoneNumber.AcceptsTab = false;
			this.club_txtPhoneNumber.AnimationSpeed = 200;
			this.club_txtPhoneNumber.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
			this.club_txtPhoneNumber.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
			this.club_txtPhoneNumber.BackColor = System.Drawing.Color.White;
			this.club_txtPhoneNumber.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("club_txtPhoneNumber.BackgroundImage")));
			this.club_txtPhoneNumber.BorderColorActive = System.Drawing.Color.DodgerBlue;
			this.club_txtPhoneNumber.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.club_txtPhoneNumber.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.club_txtPhoneNumber.BorderColorIdle = System.Drawing.Color.Silver;
			this.club_txtPhoneNumber.BorderRadius = 5;
			this.club_txtPhoneNumber.BorderThickness = 1;
			this.club_txtPhoneNumber.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
			this.club_txtPhoneNumber.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.club_txtPhoneNumber.DefaultFont = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.club_txtPhoneNumber.DefaultText = "";
			this.club_txtPhoneNumber.Enabled = false;
			this.club_txtPhoneNumber.FillColor = System.Drawing.Color.White;
			this.club_txtPhoneNumber.ForeColor = System.Drawing.Color.Black;
			this.club_txtPhoneNumber.HideSelection = true;
			this.club_txtPhoneNumber.IconLeft = null;
			this.club_txtPhoneNumber.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
			this.club_txtPhoneNumber.IconPadding = 10;
			this.club_txtPhoneNumber.IconRight = null;
			this.club_txtPhoneNumber.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
			this.club_txtPhoneNumber.Lines = new string[0];
			this.club_txtPhoneNumber.Location = new System.Drawing.Point(29, 102);
			this.club_txtPhoneNumber.MaxLength = 32767;
			this.club_txtPhoneNumber.MinimumSize = new System.Drawing.Size(1, 1);
			this.club_txtPhoneNumber.Modified = false;
			this.club_txtPhoneNumber.Multiline = false;
			this.club_txtPhoneNumber.Name = "club_txtPhoneNumber";
			stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
			stateProperties37.FillColor = System.Drawing.Color.Empty;
			stateProperties37.ForeColor = System.Drawing.Color.Empty;
			stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.club_txtPhoneNumber.OnActiveState = stateProperties37;
			stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
			stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
			stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
			this.club_txtPhoneNumber.OnDisabledState = stateProperties38;
			stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			stateProperties39.FillColor = System.Drawing.Color.Empty;
			stateProperties39.ForeColor = System.Drawing.Color.Empty;
			stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.club_txtPhoneNumber.OnHoverState = stateProperties39;
			stateProperties40.BorderColor = System.Drawing.Color.Silver;
			stateProperties40.FillColor = System.Drawing.Color.White;
			stateProperties40.ForeColor = System.Drawing.Color.Black;
			stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.club_txtPhoneNumber.OnIdleState = stateProperties40;
			this.club_txtPhoneNumber.Padding = new System.Windows.Forms.Padding(3);
			this.club_txtPhoneNumber.PasswordChar = '\0';
			this.club_txtPhoneNumber.PlaceholderForeColor = System.Drawing.Color.Silver;
			this.club_txtPhoneNumber.PlaceholderText = "Phone number";
			this.club_txtPhoneNumber.ReadOnly = false;
			this.club_txtPhoneNumber.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.club_txtPhoneNumber.SelectedText = "";
			this.club_txtPhoneNumber.SelectionLength = 0;
			this.club_txtPhoneNumber.SelectionStart = 0;
			this.club_txtPhoneNumber.ShortcutsEnabled = true;
			this.club_txtPhoneNumber.Size = new System.Drawing.Size(437, 46);
			this.club_txtPhoneNumber.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
			this.club_txtPhoneNumber.TabIndex = 20;
			this.club_txtPhoneNumber.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.club_txtPhoneNumber.TextMarginBottom = 0;
			this.club_txtPhoneNumber.TextMarginLeft = 3;
			this.club_txtPhoneNumber.TextMarginTop = 0;
			this.club_txtPhoneNumber.TextPlaceholder = "Phone number";
			this.club_txtPhoneNumber.UseSystemPasswordChar = false;
			this.club_txtPhoneNumber.WordWrap = true;
			// 
			// club_txtEmail
			// 
			this.club_txtEmail.AcceptsReturn = false;
			this.club_txtEmail.AcceptsTab = false;
			this.club_txtEmail.AnimationSpeed = 200;
			this.club_txtEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
			this.club_txtEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
			this.club_txtEmail.BackColor = System.Drawing.Color.White;
			this.club_txtEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("club_txtEmail.BackgroundImage")));
			this.club_txtEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
			this.club_txtEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.club_txtEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.club_txtEmail.BorderColorIdle = System.Drawing.Color.Silver;
			this.club_txtEmail.BorderRadius = 5;
			this.club_txtEmail.BorderThickness = 1;
			this.club_txtEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
			this.club_txtEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.club_txtEmail.DefaultFont = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.club_txtEmail.DefaultText = "";
			this.club_txtEmail.FillColor = System.Drawing.Color.White;
			this.club_txtEmail.ForeColor = System.Drawing.Color.Black;
			this.club_txtEmail.HideSelection = true;
			this.club_txtEmail.IconLeft = null;
			this.club_txtEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
			this.club_txtEmail.IconPadding = 10;
			this.club_txtEmail.IconRight = null;
			this.club_txtEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
			this.club_txtEmail.Lines = new string[0];
			this.club_txtEmail.Location = new System.Drawing.Point(29, 174);
			this.club_txtEmail.MaxLength = 32767;
			this.club_txtEmail.MinimumSize = new System.Drawing.Size(1, 1);
			this.club_txtEmail.Modified = false;
			this.club_txtEmail.Multiline = false;
			this.club_txtEmail.Name = "club_txtEmail";
			stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
			stateProperties41.FillColor = System.Drawing.Color.Empty;
			stateProperties41.ForeColor = System.Drawing.Color.Empty;
			stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.club_txtEmail.OnActiveState = stateProperties41;
			stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
			stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
			stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
			this.club_txtEmail.OnDisabledState = stateProperties42;
			stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			stateProperties43.FillColor = System.Drawing.Color.Empty;
			stateProperties43.ForeColor = System.Drawing.Color.Empty;
			stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.club_txtEmail.OnHoverState = stateProperties43;
			stateProperties44.BorderColor = System.Drawing.Color.Silver;
			stateProperties44.FillColor = System.Drawing.Color.White;
			stateProperties44.ForeColor = System.Drawing.Color.Black;
			stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.club_txtEmail.OnIdleState = stateProperties44;
			this.club_txtEmail.Padding = new System.Windows.Forms.Padding(3);
			this.club_txtEmail.PasswordChar = '\0';
			this.club_txtEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
			this.club_txtEmail.PlaceholderText = "Email";
			this.club_txtEmail.ReadOnly = false;
			this.club_txtEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.club_txtEmail.SelectedText = "";
			this.club_txtEmail.SelectionLength = 0;
			this.club_txtEmail.SelectionStart = 0;
			this.club_txtEmail.ShortcutsEnabled = true;
			this.club_txtEmail.Size = new System.Drawing.Size(437, 46);
			this.club_txtEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
			this.club_txtEmail.TabIndex = 2;
			this.club_txtEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.club_txtEmail.TextMarginBottom = 0;
			this.club_txtEmail.TextMarginLeft = 3;
			this.club_txtEmail.TextMarginTop = 0;
			this.club_txtEmail.TextPlaceholder = "Email";
			this.club_txtEmail.UseSystemPasswordChar = false;
			this.club_txtEmail.WordWrap = true;
			// 
			// club_txtAddress
			// 
			this.club_txtAddress.AcceptsReturn = false;
			this.club_txtAddress.AcceptsTab = false;
			this.club_txtAddress.AnimationSpeed = 200;
			this.club_txtAddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
			this.club_txtAddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
			this.club_txtAddress.BackColor = System.Drawing.Color.White;
			this.club_txtAddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("club_txtAddress.BackgroundImage")));
			this.club_txtAddress.BorderColorActive = System.Drawing.Color.DodgerBlue;
			this.club_txtAddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.club_txtAddress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.club_txtAddress.BorderColorIdle = System.Drawing.Color.Silver;
			this.club_txtAddress.BorderRadius = 5;
			this.club_txtAddress.BorderThickness = 1;
			this.club_txtAddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
			this.club_txtAddress.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.club_txtAddress.DefaultFont = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.club_txtAddress.DefaultText = "";
			this.club_txtAddress.FillColor = System.Drawing.Color.White;
			this.club_txtAddress.ForeColor = System.Drawing.Color.Black;
			this.club_txtAddress.HideSelection = true;
			this.club_txtAddress.IconLeft = null;
			this.club_txtAddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
			this.club_txtAddress.IconPadding = 10;
			this.club_txtAddress.IconRight = null;
			this.club_txtAddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
			this.club_txtAddress.Lines = new string[0];
			this.club_txtAddress.Location = new System.Drawing.Point(29, 246);
			this.club_txtAddress.MaxLength = 32767;
			this.club_txtAddress.MinimumSize = new System.Drawing.Size(1, 1);
			this.club_txtAddress.Modified = false;
			this.club_txtAddress.Multiline = false;
			this.club_txtAddress.Name = "club_txtAddress";
			stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
			stateProperties45.FillColor = System.Drawing.Color.Empty;
			stateProperties45.ForeColor = System.Drawing.Color.Empty;
			stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.club_txtAddress.OnActiveState = stateProperties45;
			stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
			stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
			stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
			this.club_txtAddress.OnDisabledState = stateProperties46;
			stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			stateProperties47.FillColor = System.Drawing.Color.Empty;
			stateProperties47.ForeColor = System.Drawing.Color.Empty;
			stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.club_txtAddress.OnHoverState = stateProperties47;
			stateProperties48.BorderColor = System.Drawing.Color.Silver;
			stateProperties48.FillColor = System.Drawing.Color.White;
			stateProperties48.ForeColor = System.Drawing.Color.Black;
			stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.club_txtAddress.OnIdleState = stateProperties48;
			this.club_txtAddress.Padding = new System.Windows.Forms.Padding(3);
			this.club_txtAddress.PasswordChar = '\0';
			this.club_txtAddress.PlaceholderForeColor = System.Drawing.Color.Silver;
			this.club_txtAddress.PlaceholderText = "Address";
			this.club_txtAddress.ReadOnly = false;
			this.club_txtAddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.club_txtAddress.SelectedText = "";
			this.club_txtAddress.SelectionLength = 0;
			this.club_txtAddress.SelectionStart = 0;
			this.club_txtAddress.ShortcutsEnabled = true;
			this.club_txtAddress.Size = new System.Drawing.Size(437, 46);
			this.club_txtAddress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
			this.club_txtAddress.TabIndex = 3;
			this.club_txtAddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.club_txtAddress.TextMarginBottom = 0;
			this.club_txtAddress.TextMarginLeft = 3;
			this.club_txtAddress.TextMarginTop = 0;
			this.club_txtAddress.TextPlaceholder = "Address";
			this.club_txtAddress.UseSystemPasswordChar = false;
			this.club_txtAddress.WordWrap = true;
			// 
			// club_btnCancel
			// 
			this.club_btnCancel.AllowAnimations = true;
			this.club_btnCancel.AllowMouseEffects = true;
			this.club_btnCancel.AllowToggling = false;
			this.club_btnCancel.AnimationSpeed = 200;
			this.club_btnCancel.AutoGenerateColors = false;
			this.club_btnCancel.AutoRoundBorders = false;
			this.club_btnCancel.AutoSizeLeftIcon = true;
			this.club_btnCancel.AutoSizeRightIcon = true;
			this.club_btnCancel.BackColor = System.Drawing.Color.Transparent;
			this.club_btnCancel.BackColor1 = System.Drawing.Color.DodgerBlue;
			this.club_btnCancel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("club_btnCancel.BackgroundImage")));
			this.club_btnCancel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnCancel.ButtonText = "CANCEL";
			this.club_btnCancel.ButtonTextMarginLeft = 0;
			this.club_btnCancel.ColorContrastOnClick = 45;
			this.club_btnCancel.ColorContrastOnHover = 45;
			this.club_btnCancel.Cursor = System.Windows.Forms.Cursors.Hand;
			borderEdges18.BottomLeft = true;
			borderEdges18.BottomRight = true;
			borderEdges18.TopLeft = true;
			borderEdges18.TopRight = true;
			this.club_btnCancel.CustomizableEdges = borderEdges18;
			this.club_btnCancel.DialogResult = System.Windows.Forms.DialogResult.None;
			this.club_btnCancel.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.club_btnCancel.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.club_btnCancel.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.club_btnCancel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			this.club_btnCancel.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.club_btnCancel.ForeColor = System.Drawing.Color.White;
			this.club_btnCancel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.club_btnCancel.IconLeftCursor = System.Windows.Forms.Cursors.Default;
			this.club_btnCancel.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
			this.club_btnCancel.IconMarginLeft = 11;
			this.club_btnCancel.IconPadding = 10;
			this.club_btnCancel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
			this.club_btnCancel.IconRightCursor = System.Windows.Forms.Cursors.Default;
			this.club_btnCancel.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
			this.club_btnCancel.IconSize = 25;
			this.club_btnCancel.IdleBorderColor = System.Drawing.Color.DodgerBlue;
			this.club_btnCancel.IdleBorderRadius = 1;
			this.club_btnCancel.IdleBorderThickness = 1;
			this.club_btnCancel.IdleFillColor = System.Drawing.Color.DodgerBlue;
			this.club_btnCancel.IdleIconLeftImage = null;
			this.club_btnCancel.IdleIconRightImage = null;
			this.club_btnCancel.IndicateFocus = false;
			this.club_btnCancel.Location = new System.Drawing.Point(262, 323);
			this.club_btnCancel.Name = "club_btnCancel";
			this.club_btnCancel.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.club_btnCancel.OnDisabledState.BorderRadius = 1;
			this.club_btnCancel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnCancel.OnDisabledState.BorderThickness = 1;
			this.club_btnCancel.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.club_btnCancel.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.club_btnCancel.OnDisabledState.IconLeftImage = null;
			this.club_btnCancel.OnDisabledState.IconRightImage = null;
			this.club_btnCancel.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.club_btnCancel.onHoverState.BorderRadius = 1;
			this.club_btnCancel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnCancel.onHoverState.BorderThickness = 1;
			this.club_btnCancel.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.club_btnCancel.onHoverState.ForeColor = System.Drawing.Color.White;
			this.club_btnCancel.onHoverState.IconLeftImage = null;
			this.club_btnCancel.onHoverState.IconRightImage = null;
			this.club_btnCancel.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
			this.club_btnCancel.OnIdleState.BorderRadius = 1;
			this.club_btnCancel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnCancel.OnIdleState.BorderThickness = 1;
			this.club_btnCancel.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
			this.club_btnCancel.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.club_btnCancel.OnIdleState.IconLeftImage = null;
			this.club_btnCancel.OnIdleState.IconRightImage = null;
			this.club_btnCancel.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.club_btnCancel.OnPressedState.BorderRadius = 1;
			this.club_btnCancel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnCancel.OnPressedState.BorderThickness = 1;
			this.club_btnCancel.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.club_btnCancel.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.club_btnCancel.OnPressedState.IconLeftImage = null;
			this.club_btnCancel.OnPressedState.IconRightImage = null;
			this.club_btnCancel.Size = new System.Drawing.Size(204, 88);
			this.club_btnCancel.TabIndex = 10;
			this.club_btnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.club_btnCancel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			this.club_btnCancel.TextMarginLeft = 0;
			this.club_btnCancel.TextPadding = new System.Windows.Forms.Padding(0);
			this.club_btnCancel.UseDefaultRadiusAndThickness = true;
			this.club_btnCancel.Click += new System.EventHandler(this.club_btnCancel_Click);
			// 
			// club_btnOK
			// 
			this.club_btnOK.AllowAnimations = true;
			this.club_btnOK.AllowMouseEffects = true;
			this.club_btnOK.AllowToggling = false;
			this.club_btnOK.AnimationSpeed = 200;
			this.club_btnOK.AutoGenerateColors = false;
			this.club_btnOK.AutoRoundBorders = false;
			this.club_btnOK.AutoSizeLeftIcon = true;
			this.club_btnOK.AutoSizeRightIcon = true;
			this.club_btnOK.BackColor = System.Drawing.Color.Transparent;
			this.club_btnOK.BackColor1 = System.Drawing.Color.DodgerBlue;
			this.club_btnOK.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("club_btnOK.BackgroundImage")));
			this.club_btnOK.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnOK.ButtonText = "OK";
			this.club_btnOK.ButtonTextMarginLeft = 0;
			this.club_btnOK.ColorContrastOnClick = 45;
			this.club_btnOK.ColorContrastOnHover = 45;
			this.club_btnOK.Cursor = System.Windows.Forms.Cursors.Hand;
			borderEdges19.BottomLeft = true;
			borderEdges19.BottomRight = true;
			borderEdges19.TopLeft = true;
			borderEdges19.TopRight = true;
			this.club_btnOK.CustomizableEdges = borderEdges19;
			this.club_btnOK.DialogResult = System.Windows.Forms.DialogResult.None;
			this.club_btnOK.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.club_btnOK.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.club_btnOK.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.club_btnOK.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			this.club_btnOK.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.club_btnOK.ForeColor = System.Drawing.Color.White;
			this.club_btnOK.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.club_btnOK.IconLeftCursor = System.Windows.Forms.Cursors.Default;
			this.club_btnOK.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
			this.club_btnOK.IconMarginLeft = 11;
			this.club_btnOK.IconPadding = 10;
			this.club_btnOK.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
			this.club_btnOK.IconRightCursor = System.Windows.Forms.Cursors.Default;
			this.club_btnOK.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
			this.club_btnOK.IconSize = 25;
			this.club_btnOK.IdleBorderColor = System.Drawing.Color.DodgerBlue;
			this.club_btnOK.IdleBorderRadius = 1;
			this.club_btnOK.IdleBorderThickness = 1;
			this.club_btnOK.IdleFillColor = System.Drawing.Color.DodgerBlue;
			this.club_btnOK.IdleIconLeftImage = null;
			this.club_btnOK.IdleIconRightImage = null;
			this.club_btnOK.IndicateFocus = false;
			this.club_btnOK.Location = new System.Drawing.Point(29, 323);
			this.club_btnOK.Name = "club_btnOK";
			this.club_btnOK.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.club_btnOK.OnDisabledState.BorderRadius = 1;
			this.club_btnOK.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnOK.OnDisabledState.BorderThickness = 1;
			this.club_btnOK.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.club_btnOK.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.club_btnOK.OnDisabledState.IconLeftImage = null;
			this.club_btnOK.OnDisabledState.IconRightImage = null;
			this.club_btnOK.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.club_btnOK.onHoverState.BorderRadius = 1;
			this.club_btnOK.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnOK.onHoverState.BorderThickness = 1;
			this.club_btnOK.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.club_btnOK.onHoverState.ForeColor = System.Drawing.Color.White;
			this.club_btnOK.onHoverState.IconLeftImage = null;
			this.club_btnOK.onHoverState.IconRightImage = null;
			this.club_btnOK.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
			this.club_btnOK.OnIdleState.BorderRadius = 1;
			this.club_btnOK.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnOK.OnIdleState.BorderThickness = 1;
			this.club_btnOK.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
			this.club_btnOK.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.club_btnOK.OnIdleState.IconLeftImage = null;
			this.club_btnOK.OnIdleState.IconRightImage = null;
			this.club_btnOK.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.club_btnOK.OnPressedState.BorderRadius = 1;
			this.club_btnOK.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnOK.OnPressedState.BorderThickness = 1;
			this.club_btnOK.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.club_btnOK.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.club_btnOK.OnPressedState.IconLeftImage = null;
			this.club_btnOK.OnPressedState.IconRightImage = null;
			this.club_btnOK.Size = new System.Drawing.Size(204, 88);
			this.club_btnOK.TabIndex = 9;
			this.club_btnOK.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.club_btnOK.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			this.club_btnOK.TextMarginLeft = 0;
			this.club_btnOK.TextPadding = new System.Windows.Forms.Padding(0);
			this.club_btnOK.UseDefaultRadiusAndThickness = true;
			this.club_btnOK.Click += new System.EventHandler(this.club_btnOK_Click);
			// 
			// club_btnLogOut
			// 
			this.club_btnLogOut.AllowAnimations = true;
			this.club_btnLogOut.AllowMouseEffects = true;
			this.club_btnLogOut.AllowToggling = false;
			this.club_btnLogOut.AnimationSpeed = 200;
			this.club_btnLogOut.AutoGenerateColors = false;
			this.club_btnLogOut.AutoRoundBorders = false;
			this.club_btnLogOut.AutoSizeLeftIcon = true;
			this.club_btnLogOut.AutoSizeRightIcon = true;
			this.club_btnLogOut.BackColor = System.Drawing.Color.Transparent;
			this.club_btnLogOut.BackColor1 = System.Drawing.Color.DodgerBlue;
			this.club_btnLogOut.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("club_btnLogOut.BackgroundImage")));
			this.club_btnLogOut.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnLogOut.ButtonText = "LOG OUT";
			this.club_btnLogOut.ButtonTextMarginLeft = 0;
			this.club_btnLogOut.ColorContrastOnClick = 45;
			this.club_btnLogOut.ColorContrastOnHover = 45;
			this.club_btnLogOut.Cursor = System.Windows.Forms.Cursors.Hand;
			borderEdges20.BottomLeft = true;
			borderEdges20.BottomRight = true;
			borderEdges20.TopLeft = true;
			borderEdges20.TopRight = true;
			this.club_btnLogOut.CustomizableEdges = borderEdges20;
			this.club_btnLogOut.DialogResult = System.Windows.Forms.DialogResult.None;
			this.club_btnLogOut.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.club_btnLogOut.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.club_btnLogOut.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.club_btnLogOut.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			this.club_btnLogOut.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.club_btnLogOut.ForeColor = System.Drawing.Color.White;
			this.club_btnLogOut.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.club_btnLogOut.IconLeftCursor = System.Windows.Forms.Cursors.Default;
			this.club_btnLogOut.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
			this.club_btnLogOut.IconMarginLeft = 11;
			this.club_btnLogOut.IconPadding = 10;
			this.club_btnLogOut.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
			this.club_btnLogOut.IconRightCursor = System.Windows.Forms.Cursors.Default;
			this.club_btnLogOut.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
			this.club_btnLogOut.IconSize = 25;
			this.club_btnLogOut.IdleBorderColor = System.Drawing.Color.DodgerBlue;
			this.club_btnLogOut.IdleBorderRadius = 1;
			this.club_btnLogOut.IdleBorderThickness = 1;
			this.club_btnLogOut.IdleFillColor = System.Drawing.Color.DodgerBlue;
			this.club_btnLogOut.IdleIconLeftImage = null;
			this.club_btnLogOut.IdleIconRightImage = null;
			this.club_btnLogOut.IndicateFocus = false;
			this.club_btnLogOut.Location = new System.Drawing.Point(262, 445);
			this.club_btnLogOut.Name = "club_btnLogOut";
			this.club_btnLogOut.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.club_btnLogOut.OnDisabledState.BorderRadius = 1;
			this.club_btnLogOut.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnLogOut.OnDisabledState.BorderThickness = 1;
			this.club_btnLogOut.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.club_btnLogOut.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.club_btnLogOut.OnDisabledState.IconLeftImage = null;
			this.club_btnLogOut.OnDisabledState.IconRightImage = null;
			this.club_btnLogOut.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.club_btnLogOut.onHoverState.BorderRadius = 1;
			this.club_btnLogOut.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnLogOut.onHoverState.BorderThickness = 1;
			this.club_btnLogOut.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.club_btnLogOut.onHoverState.ForeColor = System.Drawing.Color.White;
			this.club_btnLogOut.onHoverState.IconLeftImage = null;
			this.club_btnLogOut.onHoverState.IconRightImage = null;
			this.club_btnLogOut.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
			this.club_btnLogOut.OnIdleState.BorderRadius = 1;
			this.club_btnLogOut.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnLogOut.OnIdleState.BorderThickness = 1;
			this.club_btnLogOut.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
			this.club_btnLogOut.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.club_btnLogOut.OnIdleState.IconLeftImage = null;
			this.club_btnLogOut.OnIdleState.IconRightImage = null;
			this.club_btnLogOut.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.club_btnLogOut.OnPressedState.BorderRadius = 1;
			this.club_btnLogOut.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnLogOut.OnPressedState.BorderThickness = 1;
			this.club_btnLogOut.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.club_btnLogOut.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.club_btnLogOut.OnPressedState.IconLeftImage = null;
			this.club_btnLogOut.OnPressedState.IconRightImage = null;
			this.club_btnLogOut.Size = new System.Drawing.Size(204, 88);
			this.club_btnLogOut.TabIndex = 12;
			this.club_btnLogOut.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.club_btnLogOut.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			this.club_btnLogOut.TextMarginLeft = 0;
			this.club_btnLogOut.TextPadding = new System.Windows.Forms.Padding(0);
			this.club_btnLogOut.UseDefaultRadiusAndThickness = true;
			this.club_btnLogOut.Click += new System.EventHandler(this.club_btnLogOut_Click);
			// 
			// club_btnBackHome
			// 
			this.club_btnBackHome.AllowAnimations = true;
			this.club_btnBackHome.AllowMouseEffects = true;
			this.club_btnBackHome.AllowToggling = false;
			this.club_btnBackHome.AnimationSpeed = 200;
			this.club_btnBackHome.AutoGenerateColors = false;
			this.club_btnBackHome.AutoRoundBorders = false;
			this.club_btnBackHome.AutoSizeLeftIcon = true;
			this.club_btnBackHome.AutoSizeRightIcon = true;
			this.club_btnBackHome.BackColor = System.Drawing.Color.Transparent;
			this.club_btnBackHome.BackColor1 = System.Drawing.Color.DodgerBlue;
			this.club_btnBackHome.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("club_btnBackHome.BackgroundImage")));
			this.club_btnBackHome.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnBackHome.ButtonText = "HOME";
			this.club_btnBackHome.ButtonTextMarginLeft = 0;
			this.club_btnBackHome.ColorContrastOnClick = 45;
			this.club_btnBackHome.ColorContrastOnHover = 45;
			this.club_btnBackHome.Cursor = System.Windows.Forms.Cursors.Hand;
			borderEdges21.BottomLeft = true;
			borderEdges21.BottomRight = true;
			borderEdges21.TopLeft = true;
			borderEdges21.TopRight = true;
			this.club_btnBackHome.CustomizableEdges = borderEdges21;
			this.club_btnBackHome.DialogResult = System.Windows.Forms.DialogResult.None;
			this.club_btnBackHome.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.club_btnBackHome.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.club_btnBackHome.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.club_btnBackHome.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			this.club_btnBackHome.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.club_btnBackHome.ForeColor = System.Drawing.Color.White;
			this.club_btnBackHome.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.club_btnBackHome.IconLeftCursor = System.Windows.Forms.Cursors.Default;
			this.club_btnBackHome.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
			this.club_btnBackHome.IconMarginLeft = 11;
			this.club_btnBackHome.IconPadding = 10;
			this.club_btnBackHome.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
			this.club_btnBackHome.IconRightCursor = System.Windows.Forms.Cursors.Default;
			this.club_btnBackHome.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
			this.club_btnBackHome.IconSize = 25;
			this.club_btnBackHome.IdleBorderColor = System.Drawing.Color.DodgerBlue;
			this.club_btnBackHome.IdleBorderRadius = 1;
			this.club_btnBackHome.IdleBorderThickness = 1;
			this.club_btnBackHome.IdleFillColor = System.Drawing.Color.DodgerBlue;
			this.club_btnBackHome.IdleIconLeftImage = null;
			this.club_btnBackHome.IdleIconRightImage = null;
			this.club_btnBackHome.IndicateFocus = false;
			this.club_btnBackHome.Location = new System.Drawing.Point(29, 445);
			this.club_btnBackHome.Name = "club_btnBackHome";
			this.club_btnBackHome.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.club_btnBackHome.OnDisabledState.BorderRadius = 1;
			this.club_btnBackHome.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnBackHome.OnDisabledState.BorderThickness = 1;
			this.club_btnBackHome.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.club_btnBackHome.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.club_btnBackHome.OnDisabledState.IconLeftImage = null;
			this.club_btnBackHome.OnDisabledState.IconRightImage = null;
			this.club_btnBackHome.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.club_btnBackHome.onHoverState.BorderRadius = 1;
			this.club_btnBackHome.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnBackHome.onHoverState.BorderThickness = 1;
			this.club_btnBackHome.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.club_btnBackHome.onHoverState.ForeColor = System.Drawing.Color.White;
			this.club_btnBackHome.onHoverState.IconLeftImage = null;
			this.club_btnBackHome.onHoverState.IconRightImage = null;
			this.club_btnBackHome.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
			this.club_btnBackHome.OnIdleState.BorderRadius = 1;
			this.club_btnBackHome.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnBackHome.OnIdleState.BorderThickness = 1;
			this.club_btnBackHome.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
			this.club_btnBackHome.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.club_btnBackHome.OnIdleState.IconLeftImage = null;
			this.club_btnBackHome.OnIdleState.IconRightImage = null;
			this.club_btnBackHome.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.club_btnBackHome.OnPressedState.BorderRadius = 1;
			this.club_btnBackHome.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.club_btnBackHome.OnPressedState.BorderThickness = 1;
			this.club_btnBackHome.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.club_btnBackHome.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.club_btnBackHome.OnPressedState.IconLeftImage = null;
			this.club_btnBackHome.OnPressedState.IconRightImage = null;
			this.club_btnBackHome.Size = new System.Drawing.Size(204, 88);
			this.club_btnBackHome.TabIndex = 11;
			this.club_btnBackHome.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.club_btnBackHome.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			this.club_btnBackHome.TextMarginLeft = 0;
			this.club_btnBackHome.TextPadding = new System.Windows.Forms.Padding(0);
			this.club_btnBackHome.UseDefaultRadiusAndThickness = true;
			this.club_btnBackHome.Click += new System.EventHandler(this.club_btnBackHome_Click);
			// 
			// bunifuGradientPanel2
			// 
			this.bunifuGradientPanel2.BackColor = System.Drawing.Color.Transparent;
			this.bunifuGradientPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel2.BackgroundImage")));
			this.bunifuGradientPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
			this.bunifuGradientPanel2.BorderRadius = 1;
			this.bunifuGradientPanel2.Controls.Add(this.club_btnBackHome);
			this.bunifuGradientPanel2.Controls.Add(this.club_btnLogOut);
			this.bunifuGradientPanel2.Controls.Add(this.club_btnOK);
			this.bunifuGradientPanel2.Controls.Add(this.club_btnCancel);
			this.bunifuGradientPanel2.Controls.Add(this.club_txtAddress);
			this.bunifuGradientPanel2.Controls.Add(this.club_txtEmail);
			this.bunifuGradientPanel2.Controls.Add(this.club_txtPhoneNumber);
			this.bunifuGradientPanel2.Controls.Add(this.club_txtNameClub);
			this.bunifuGradientPanel2.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(92)))), ((int)(((byte)(188)))));
			this.bunifuGradientPanel2.GradientBottomRight = System.Drawing.Color.DeepPink;
			this.bunifuGradientPanel2.GradientTopLeft = System.Drawing.Color.DodgerBlue;
			this.bunifuGradientPanel2.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(198)))), ((int)(((byte)(60)))), ((int)(((byte)(212)))));
			this.bunifuGradientPanel2.Location = new System.Drawing.Point(198, 0);
			this.bunifuGradientPanel2.Name = "bunifuGradientPanel2";
			this.bunifuGradientPanel2.Quality = 10;
			this.bunifuGradientPanel2.Size = new System.Drawing.Size(494, 553);
			this.bunifuGradientPanel2.TabIndex = 12;
			// 
			// frmClub
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new System.Drawing.Size(691, 554);
			this.Controls.Add(this.bunifuGradientPanel2);
			this.Controls.Add(this.bunifuGradientPanel1);
			this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
			this.Name = "frmClub";
			this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "UEFA Champions League";
			this.Load += new System.EventHandler(this.frmClub_Load);
			((System.ComponentModel.ISupportInitialize)(this.club_ptbLogo)).EndInit();
			this.bunifuGradientPanel1.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.club_ptbAwayJersey)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.club_ptbHomeJersey)).EndInit();
			this.bunifuGradientPanel2.ResumeLayout(false);
			this.ResumeLayout(false);

		}

		#endregion

		private Bunifu.UI.WinForms.BunifuPictureBox club_ptbLogo;
		private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton club_btnUploadLogo;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton club_btnUploadAwayJersey;
		private Bunifu.UI.WinForms.BunifuPictureBox club_ptbAwayJersey;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton club_btnUploadHomeJersey;
		private Bunifu.UI.WinForms.BunifuPictureBox club_ptbHomeJersey;
		private Bunifu.UI.WinForms.BunifuTextBox club_txtNameClub;
		private Bunifu.UI.WinForms.BunifuTextBox club_txtPhoneNumber;
		private Bunifu.UI.WinForms.BunifuTextBox club_txtEmail;
		private Bunifu.UI.WinForms.BunifuTextBox club_txtAddress;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton club_btnCancel;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton club_btnOK;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton club_btnLogOut;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton club_btnBackHome;
		private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel2;
	}
}